### ISSUE TITLE
Closing modal doesn't animate out, closes instantly after duration

### ISSUE THREAD

**Issue by okcompewter** [colorfy-software/react-native-modalfy#26] opened 2020-09-07 06:26 UTC
When calling closeModal(), the closing animation never happens. It waits the amount of time of the duration, then instantly closes. I've tested this by setting the duration to 3 seconds... there is no visible transition happening when closing.

This problem however doesn't exist on openModal(), which works fine.

```
  const defaultOptions: ModalOptions = {
    backdropOpacity: 0.9,
    disableFlingGesture: true,
    animateInConfig: {
      easing: Easing.inOut(Easing.exp),
      duration: 3000,
    },
    animateOutConfig: {
      easing: Easing.inOut(Easing.exp),
      duration: 3000,
    }
  }
```

Any ideas?

**Comment by okcompewter** [comment] 2020-09-07 06:43
It also seems that the **animateInConfig** in the **defaultOptions** has no effect (adjusting the duration to 5000, the modal still fades in within a second)

**Comment by CharlesMangwa** [comment] 2020-09-26 12:18
Hi @okcompewter! Could you provide a reproducible demo in [Snack](https://snack.expo.io) plz? Would make it easier to debug your issue. Thanks!

**Comment by CharlesMangwa** [comment] 2020-10-17 07:43
Closing this issue for now, feel free to reopen as soon as you'll have the repro.

**Comment by smoove** [comment] 2021-09-20 15:30
> Closing this issue for now, feel free to reopen as soon as you'll have the repro.

https://snack.expo.dev/@charles.m/react-native-modalfy

Opening is animated, closing is not.

**Comment by smoove** [comment] 2021-09-20 15:34
> Closing this issue for now, feel free to reopen as soon as you'll have the repro.

It does not work in the demo snack (remove animateOutConfig, or set value > 0 @ line 49)

https://snack.expo.dev/@charles.m/react-native-modalfy

**Comment by CharlesMangwa** [comment] 2021-10-04 11:22
Thanks for the heads up! You're right, we'll have to look into this.

**Comment by facuescobar** [comment] 2021-11-11 15:13
Hi guys! 
I'm having the same issue, closing animation does not work.

My modal animates the modal from the bottom, but when closeModal() is called, it disapears without animation.

```js
const defaultOptions = {
  backdropOpacity: 0.75,
  position: 'bottom',
  animateOutConfig: {
    easing: Easing.inOut(Easing.exp),
    duration: 300,
  },
  transitionOptions: (animatedValue: any) => ({
    transform: [
      {
        translateY: animatedValue.interpolate({
          inputRange: [0, 1, 2],
          outputRange: [height, 0, height],
        }),
      },
    ],
  }),
};
```

I'm using 
```js
    "react-native": "0.66.0",
    "react-native-modalfy": "^2.1.2",
```

Any idea how to get the animation-out working?

**Comment by facuescobar** [comment] 2021-11-11 20:52
I found a workaround for this,
It seems that the animation does not work when you use `closeModal` function from `useModal` hook.

But if you use `closeModal` that you receive as a prop in your modal screen the animation out works!

```js
const ModalScreen = (modal: {closeModal, currentModal}) => {
    const handleTransparentBackPress = () => {
        // NOTE: closeModal won't animate-out the screen if the modal name is not sent as param
        closeModal(currentModal);
  };

}
```

**Comment by teivienn** [comment] 2021-12-14 11:56
Hi!
I have the same problem. Solution offered @facuescobar working only when my modal include custom button for closing.
I patched library and it's for work for me

<img width="702" alt="Screenshot 2021-12-14 at 14 50 40" src="https://user-images.githubusercontent.com/30047592/145993776-61666cbb-ebdc-4772-a4e8-fc2ae48dab52.png">
e

**Comment by okcompewter** [comment] 2021-12-17 18:54
@teivienn - I don't see that code anywhere in the package, where did you add/update that?

**Comment by teivienn** [comment] 2021-12-17 19:49
@okcompewter 
lib/StackItem.tsx
line 146

https://github.com/colorfy-software/react-native-modalfy/blob/1dda9c1f65fd076f61d61b46f592fb05d230b7a3/lib/StackItem.tsx#L146

**Comment by okcompewter** [comment] 2021-12-17 20:13
ah - my search wasn't picking it up for some reason, thanks!

**Comment by Omelyan** [comment] 2022-01-19 15:42
Besides that, background (container) fades in, but does not fade out, instead it instantly disappears... Also, there is no animation at all when pressing physical back button. Authors seems to be blind. So much blah-blah-blah on their introductory website, and so many primitive (!) bugs...
npm uninstall.

**Comment by fermmm** [comment] 2022-01-28 05:42
npm uninstall

**Comment by CharlesMangwa** [comment] 2022-02-15 11:28
Hey everyone! First things first, thank you all for your patience regarding this (really) long-standing issue. I'm pleased to announce that all the bugs you've mentioned in this issue have been addressed (ce6040f2170a6a9c106392ef98f3e101fedcfc6c • 091c9afc030364db94e6eadbe1a31ba8f0071d7c • 3bdc9df52edce52d9e54b94f6873ebff758860d9). These fixes are available in [the freshly released Modalfy v3](https://colorfy-software.gitbook.io/react-native-modalfy/blog/unveiling-modalfy-v3) 🥳 If you're still using Modalfy, please give it a try and let us know!

@facuescobar Thank you for pointing us in the right direction for the fix! It actually helped us uncover some other bugs 🙌 

@fermmm Glad to know that you were able to find an easier way to handle modals that worked for you! At the end of the day, using libraries is sometimes a tradeoff that's not worth taking indeed.

@Omelyan Thanks for the feedback, there were quite some annoying bugs indeed. Now I'm especially happy to read that you were also able to pick onto so other bugs that were still going under the radar. I can't wait to review your pull requests addressing all the primitives bugs you've found!

**Closed by CharlesMangwa** 2022-02-15 11:28 UTC
Labels: bug

**Comment by Omelyan** [comment] 2022-02-15 14:55
@CharlesMangwa Cool, but no visible changes)) still no animation on closing modal, no animation on physical Back press, but now it throws an exception on pressing background: "[object object] is not a valid modal name. Did you mean any of these..."
version #3 and still unusable...

**Comment by CharlesMangwa** [comment] 2022-02-15 18:26
Hey @Omelyan, thanks for the feedback: that sounds quite annoying indeed!

So about the animations, I'd suggest double-checking how you've set up your different animations inside the root modal stack config. As you may know, by default: Modalfy does not provide any animation because you might just not want any. So if there's an error on your end on that side, no animation will occur.

Regarding the exception you got, at first glance, it seems that you're calling `openModal()` or `closeModal()` and proving an object instead of a string as the initial argument. If this is however coming from the library, feel free to provide a reproducible demo if you have time and I'll be more than happy to look into it and release a patch that'd address the issues you're facing.

**Overall, however, all of the issues you've mentioned seem to be on your side as [none of them are reproducible in the updated Expo demo](https://snack.expo.dev/@charles.m/react-native-modalfy)**. But please, do correct me if I missed something!

As well: thanks a lot for taking the time to check out Modalfy v3 so quickly right after its release!

**Comment by tp26610** [comment] 2022-04-08 16:46
Hi, @CharlesMangwa 

I've reproduced the issue while calling `closeModal`.

The video is showing that animation doesn't work while calling `closeModal` and the animation works while user clicks background to dismiss the modal.

The code is here: https://snack.expo.dev/@tp26610/react-native-modalfy

https://user-images.githubusercontent.com/9457401/162485480-6b794759-87a2-43c5-bdbe-2467a0cdc6fc.mov

**Comment by CharlesMangwa** [comment] 2022-04-24 08:03
Hey @tp26610! Thanks for reaching out. I look into the issue you reported and it seems like the origin of the error is actually displayed in the video you shared.

As you can see in your repro, the `onPress` is highlighted as an error by TypeScript. If you look into why it's complaining, you'd get this: 

<img width="895" alt="Screenshot 2022-04-24 at 09 58 38" src="https://user-images.githubusercontent.com/8975443/164966369-de653ba5-4163-4d03-b3cc-09c8809c4df8.png">

By writing `onPress={closeModal}`, you're calling `closeModal()` with a `GestureResponderEvent` as 1st argument, where `closeModal()` expects a modal name string (or just `undefined`). The "fix" is to simply call the function instead of using the shorthand which makes the error goe away and the `TouchableOpacity` button work:

<img width="246" alt="Screenshot 2022-04-24 at 10 01 37" src="https://user-images.githubusercontent.com/8975443/164966442-366380b3-b17b-46ed-a183-d4750996aac3.png">

**Comment by tp26610** [comment] 2022-04-27 03:06
@CharlesMangwa Yeah, this way fixes the animation for modal. There is another after do that. The background doesn't fade out for the alpha value while calling `closeModal` like video below:

https://user-images.githubusercontent.com/9457401/165431660-cb1cc6c0-bed7-41e9-bfb9-e4242e2bd64b.mov

**Comment by CharlesMangwa** [comment] 2022-04-27 04:21
Hi @tp26610! Please simply update your project to [**`v3.2.0`**](https://github.com/colorfy-software/react-native-modalfy/releases/tag/v3.2.0), that issue has already been fixed there:


https://user-images.githubusercontent.com/8975443/165439754-a31eec74-003d-47a4-9cba-103425be7e3d.mov
